pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.8'

  - task: Npm@1
    displayName: 'npm ci'
    inputs:
      command: custom
      customCommand: ci

  - task: Npm@1
    displayName: 'npm run build-prod'
    inputs:
      command: custom
      customCommand: run build-prod

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
      includeRootFolder: false

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        build.zip
        ./scripts/build.sh
      TargetFolder: '$(Build.ArtifactStagingDirectory)'


  # https://docs.microsoft.com/pl-pl/azure/devops/pipelines/languages/javascript?view=vsts&tabs=yaml
  - task: PublishBuildArtifacts@1
