# Build Docker image for this app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'

  - task: Npm@1
    displayName: 'npm ci'
    inputs:
      command: ci

  - task: Npm@1
    displayName: 'npm run build-prod'
    inputs:
      command: run build-prod

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/build'
