# Build Docker image for this app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - script: |
      docker build --build-arg APP_ID=$(APP_ID) \
                   --build-arg CLIEND_ID=$(CLIENT_ID) \
                   --build-arg CLIENT_SECRET=$(CLIENT_SECRET) \
                   --build-arg AUTH_CODE=$(AUTH_CODE)
