pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.15'

  - task: Npm@1
    displayName: 'npm ci'
    inputs:
      command: custom
      customCommand: ci

  - task: Npm@1
    displayName: 'npm lint'
    inputs:
      command: custom
      customCommand: run lint

  - task: Npm@1
    displayName: 'npm run build-prod'
    inputs:
      command: custom
      customCommand: run build-prod

  - script: |
      PACKAGE_VERSION=$(node -p "require('./package.json').version")
      echo '##vso[task.setvariable variable=myVariable]'"${PACKAGE_VERSION}"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(PACKAGE_VERSION).$(Build.BuildId).zip'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        build.zip
        scripts/*
      TargetFolder: '$(Build.ArtifactStagingDirectory)'


  # https://docs.microsoft.com/pl-pl/azure/devops/pipelines/languages/javascript?view=vsts&tabs=yaml
  - task: PublishBuildArtifacts@1
