# Build Docker image for this app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'

  - script: node --version

  - task: Npm@1
    displayName: 'npm ci'
    inputs:
      command: ci

  - task: Npm@1
    displayName: 'npm run build-prod'
    inputs:
      command: run build-prod

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
      includeRootFolder: false

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        build.zip
      TargetFolder: '$(Build.ArtifactStagingDirectory)'


  # https://docs.microsoft.com/pl-pl/azure/devops/pipelines/languages/javascript?view=vsts&tabs=yaml
  - task: PublishBuildArtifacts@1
